version: '3'
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./db/mysql:/var/lib/mysql"
      - "./db/initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd

  web:
    build: cultural-festival
    ports:
      - 8080:8080
      - 3000:3000
    depends_on:
      - db  